---
resources:
- name: cli-plugin-echo-master
  type: git
  source:
    uri: https://github.com/EngineerBetter/cli-plugin-echo.git
    branch: master

jobs:
- name: cli-plugin-echo
  plan:
  - get: cli-plugin-echo-master
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: cli-plugin-echo-master
      run:
        path: cli-plugin-echo-master/ci/scripts/test